# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:24:24+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Path

from models import Comic

app = MCPProxy(
    description='Webcomic of romance, sarcasm, math, and language.',
    title='XKCD',
    version='1.0.0',
    servers=[{'url': 'http://xkcd.com/'}],
)


@app.get(
    '/info.0.json',
    description=""" Fetch current comic and metadata.
 """,
    tags=['general_data_access'],
)
def get_info_0_json():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/{comicId}/info.0.json',
    description=""" Fetch comics and metadata  by comic id.
 """,
    tags=['comic_detail_fetching'],
)
def get__comic_id_info_0_json(comic_id: float = Path(..., alias='comicId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
