# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:24:24+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Comic(BaseModel):
    alt: Optional[str] = None
    day: Optional[str] = None
    img: Optional[str] = None
    link: Optional[str] = None
    month: Optional[str] = None
    news: Optional[str] = None
    num: Optional[float] = None
    safe_title: Optional[str] = None
    title: Optional[str] = None
    transcript: Optional[str] = None
    year: Optional[str] = None
